replicaCount: 3

image:
  repository: learnkube
  tag: v1
  pullPolicy: IfNotPresent

appVersion: v1

greeting: Hello

persistence:
  size: 1Gi
  storageClassName: ""

service:
  type: NodePort
  port: 8080

resources: {}
