apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-learnkube
  labels:
    app: {{ .Release.Name }}-learnkube
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-learnkube
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-learnkube
    spec:
      initContainers:
        - name: logshipper
          restartPolicy: Always
          image: busybox:1.36
          command: ["sh", "-c", "touch /var/log/learnkube/app.log && tail -F /var/log/learnkube/app.log"]
          volumeMounts:
            - name: logs
              mountPath: /var/log/learnkube
      containers:
        - name: learnkube
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: {{ .Values.appVersion | quote }}
          volumeMounts:
            - name: config
              mountPath: /etc/config
              readOnly: true
            - name: logs
              mountPath: /var/log/learnkube
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-learnkube-config
        - name: logs
          emptyDir: {}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-learnkube-data
