apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: learnkube
spec:
  serviceName: learnkube-headless
  replicas: 3
  selector:
    matchLabels:
      app: learnkube-stateful
  template:
    metadata:
      labels:
        app: learnkube-stateful
    spec:
      containers:
        - name: learnkube
          image: learnkube:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: "v1"
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
